### ISSUE TITLE
블로그 가이드라인 추가

### ISSUE THREAD

**Issue by syleeie2310** [KaggleBreak/gatsby-casper#1]
## Summary
블로그 가이드 라인 추가

## Todo
준영님과 이야기 하여 상세 가이드 라인 자것ㅇ

**Comment by Swalloow** [comment]
master 브랜치에 바로 push 하게 되면 바로 배포가 되기 때문에 의미가 없습니다.
아래와 같은 과정이 좋을 듯 합니다.

1. develop 브랜치에 push
2. master 브랜치로 pull request를 생성, 리뷰
3. 빌드와 리뷰가 통과되면 master로 merge
