### ISSUE TITLE
한글 폰트 교체

### ISSUE THREAD

**Issue by syleeie2310** [KaggleBreak/gatsby-casper#10]
## Summary
마크다운 폰트 교체

## Todo
블로그의 한글 폰트 전반적으로 교체했으면 좋겠습니다! 방법이 없을까요? 
적절한 폰트를 찾아주세요 ㅜㅜ

## Importance
하

**Comment by Swalloow** [comment]
@syleeie2310 

무난하게 나눔고딕으로 해도 되나요?
다른 폰트 원하시면 아래 링크에서 찾아보셔도 됩니다!
https://fonts.google.com/specimen/Nanum+Gothic

**Comment by syleeie2310** [comment]
@Swalloow  네 나눔 고딕 하시면 됩니다! 감사합니다 :)
