### ISSUE TITLE
베이지안 A/B 테스트의 장점

### ISSUE THREAD

**Issue by kaylee123** [KaggleBreak/gatsby-casper#12]
## Title & Topic

베이지안 A/B 테스트의 장점

## Upload schedule

작성시작날짜 4/5 
업로드계획날짜 4/7

## Reference

https://medium.com/convoy-tech/the-power-of-bayesian-a-b-testing-f859d2219d5

**Comment by syleeie2310** [comment]
이건 이슈 종료해주시고 https://github.com/KaggleBreak/databreak-blog/issues 에 새롭게 올려주세요

@kaylee123
