### ISSUE TITLE
kdnuggets - Data Scientist’s Dilemma: The Cold Start Problem 아티클 리뷰

### ISSUE THREAD

**Issue by syleeie2310** [KaggleBreak/gatsby-casper#2]
## Title & Topic
Data Scientist’s Dilemma: The Cold Start Problem – Ten Machine Learning Examples

## Upload schedule
2019/03/17일까지

## Reference
https://www.kdnuggets.com/2019/01/data-scientist-dilemma-cold-start-machine-learning.html

**Comment by Swalloow** [comment]
@syleeie2310 
tags 메타정보를 tags.yaml에 추가해주셔야 합니다.
배포 과정에서 빌드 오류가 발생했는데 앞으로는 로컬에서 빌드가 되는지 먼저 확인 부탁드립니다.
오류는 제가 수정해서 올렸습니다.

**Comment by Swalloow** [comment]
@syleeie2310 
- 콜드 스타트를 해결하기 위한 방법 (...) 이 부분은 의도하신건가요? 내용이 없네요
- 얼어 붙은 아침에 아주 차가운 차를 운전하려고 시도해본 사람이라면 누구든지 추위에 시달리는 기세의 고통을 안다.
(문어체 또는 구어체 둘 중 하나로 통일하면 좋을 것 같습니다)
