### ISSUE TITLE
Sebastian Ruder's blog - 10 Exciting Ideas of 2018 in NLP 포스트 리뷰

### ISSUE THREAD

**Issue by Chogyuwon** [KaggleBreak/gatsby-casper#3]
## Title & Topic

Title : 10 Exciting Ideas of 2018 in NLP
Topic : NLP

## Upload schedule

작성 시작 날짜 : 2019-03-18
업로드 계획 : 2019-03-28

## Reference

http://ruder.io/10-exciting-ideas-of-2018-in-nlp/

**Comment by syleeie2310** [comment]
제가 보고 답글 남길게요!! 고생하셨어요 첫 작업하느라 ㅎㅎ

**Comment by syleeie2310** [comment]
distilling(증류)?
=> 이건 그냥 증류라는 말을 빼도 되지 않을까요? 증류라는 말이 공식으로 쓰이는 단어가 아니면 괜히 어색해서, 번역기 돌린 느낌이라서 빼도 될 것 같아요!
그냥 이렇게만 표현하면 어떨까요? distilling(불필요한 것을 걷어내고 핵심만 추출) 

이 세가지 핵심 요소들은 이 후 보게 될 다른 비지도 학습 시나리오에 대해서도 도움이 될 것입니다. 
=> 이 세가지 핵심 요소들은 이후 보게 될 다른 비지도 학습 시나리오에 대해서도 도움이 될 것입니다. 
(띄어쓰기 문제) 

유사성을 계산하는 모델을 사용해제한된 최적화 문제를 풀어야 가능합니다.
=> 유사성을 계산하는 모델을 사용해 제한된 최적화 문제를 풀어야 가능합니다.
(띄어쓰기 문제) 

퓨샷러닝(few-shot learning)
=> 그냥 few-shot learning  만 쓰는게 자연스러울 것 같아요


고생하셨습니다! 이정도 리뷰로 끝낼게요.. 내용은 한번 다음 모임 때 설명해주시고, 4월에는 다음 글 준비해주심 될것 같아요.

수정 완료하시면 해당 글 요약하셔서 이번주에 페이스북에 포스팅 해주세요!

(페이스북 포스팅은 아래 참고할 것 : https://www.facebook.com/groups/databreak/permalink/2337634946491174/)

**Comment by Chogyuwon** [comment]
상열님

이번주 중으로 말씀하신 수정사항 반영해서
업데이트 후 페북에 포스팅 하도록 하겠습니다.

리뷰해주시느라 고생많으셨습니다!

감사합니다.

조규원 드림

2019년 3월 25일 (월) 오후 8:12, syleeie <notifications@github.com>님이 작성:
