### ISSUE TITLE
Combining multiple feature selection methods for stock prediction Review 

### ISSUE THREAD

**Issue by RyanYS** [KaggleBreak/gatsby-casper#4]
## Title & Topic

Title : Combining multiple feature selection methods for stock prediction :
         Union, intersection, and multi-intersection approaches
Topic : Feature Selection

## Upload schedule

작성 시작 날짜 : 2019-03-21
업로드 계획 : 2019-03-28
## Reference

https://xhxt2008.live/2017/12/21/Combining-feature-selection/#GA-SVM

**Comment by syleeie2310** [comment]
@RyanYS 님 혹시 해결하셨나요?? 리뷰 해드려야 하는데 어여 부탁드려요!!ㅎㅎ

**Comment by syleeie2310** [comment]
이해할 수있을뿐만 아니라
=> 이해할 수 있을 뿐만 아니라

파마의 효율적인 시장 가설
=> 다음과 같이 추가적인 정보 주기 
=> [Efficient-market hypothesis](https://en.wikipedia.org/wiki/Efficient-market_hypothesis)

$ g \ left (Y, A) \ right) = H \ left (Y \ right) -H \ left (Y | A \ right) $
=> 수식이 제대로 안들어갔어요, 확인해주세요!

@RyanYS  님 리뷰 끝났습니다~

저거 수정해서, 다시 푸시하시고 가이드라인 업데이트 했는데 참고하셔서 페이스북에 포스팅 해주세요
https://github.com/KaggleBreak/gatsby-casper/blob/master/GUIDELINE.md

해당 블로그 금요일날 혹시 오시면 리뷰 가능하겠죠?.? 부탁드려요!

**Comment by RyanYS** [comment]
1, 2는 수정했고 세번째꺼는 논문에 없는, 아티클에만 있는 수식이라 삭제 했습니다!

수정 후 푸쉬 하였고 페이스북 포스팅 하겠습니다.
제 아티클은 금요일에 리뷰 가능합니다 ㅎ

**Comment by syleeie2310** [comment]
네 감사합니다 @RyanYS  바로 포스팅 해주시면 되요! 페이스북에다가
금요일날 리뷰 해주세요!
