### ISSUE TITLE
Meet Michelangelo: Uber’s Machine Learning Platform

### ISSUE THREAD

**Issue by inahjeon** [KaggleBreak/gatsby-casper#5]
## Title & Topic
Meet Michelangelo: Uber’s Machine Learning Platform

## Upload schedule
2019.03.23 작성 시작 
2019.03.31 업로드 예정

## Reference
https://eng.uber.com/michelangelo/

**Comment by syleeie2310** [comment]
@inahjeon  님 혹시 올리셨나요?? 리뷰 해드려야 하는데 어여 부탁드려요!!ㅎㅎ

**Comment by inahjeon** [comment]
넵 ㅠ 오늘 업로드 예정입니다 🙏

**Comment by syleeie2310** [comment]
네 금요일 전까지 올려주시면 @inahjeon 님 제가 리뷰해드릴게요 :) 금요일 날 혹시 오실 수 없나요?.?

**Comment by inahjeon** [comment]
금요일에 참석할 수 있어요!

**Comment by syleeie2310** [comment]
ware house
=> warehouse

Cassandra애 미리 계산해서 저장해두었습니다.
=> Cassandra에 미리 계산해서 저장해두었습니다.

@inahjeon 님 리뷰 끝났습니다~  내용이 너무 좋아서 ㅎㅎ 별 이슈 없는것 같아 고생하셨습니다~
저거 수정해서, 다시 푸시하시고 가이드라인 업데이트 했는데 참고하셔서 페이스북에 포스팅 해주세요 https://github.com/KaggleBreak/gatsby-casper/blob/master/GUIDELINE.md

페이스북 포스팅 하시고 이슈 종료하고 새로운 이슈 파시면 됩니다!

**Comment by inahjeon** [comment]
넵 리뷰 감사합니다! 말씀해주신 부분 수정해서 내일 업로드 할게요 ㅎ

**Comment by syleeie2310** [comment]
수정하시면 https://github.com/KaggleBreak/databreak-blog/issues 에 새롭게 올려주시고 거기다가 md 파일 push 하시고 저한테 리뷰 요청 해주세요!

@inahjeon
