### ISSUE TITLE
Do you know how to choose the right machine learning algorithm among 7 different types?

### ISSUE THREAD

**Issue by choco9966** [KaggleBreak/gatsby-casper#6]
## Title & Topic

머신러닝 모델을 사용할 때,  데이터에 알맞는 알고리즘을 사용하는게 중요한데 이번 아티클은 이와 관련된 내용입니다.  

## Upload schedule

2019.03.22에 시작하여 2019.03.24일에 업로드 할 계획입니다.  

## Reference

https://towardsdatascience.com/do-you-know-how-to-choose-the-right-machine-learning-algorithm-among-7-different-types-295d0b0c7f60

**Comment by choco9966** [comment]
원래 지난번 발표한 것 토대로 변수선택기법들 정리해서 올리려고 했는데, 자료 찾을게 생각보다 많아서 그 주제는 4월에 올릴게여...!

**Comment by syleeie2310** [comment]
전반적으로 띄어쓰기만 잘 고치면 좋은 포스팅이 될 것 같아요.!  고생하셨습니다.

그리고 다음에 진행하실 때는 reference 하는 원작 포스팅이 좀 더 좁은 범위로 산정하시면 어떨까 생각해요. 소개하는 포스팅이 너무 전반적인 머신러닝 이야기를 짧게 소개하는 내용이라 별 내용이 없는 것 같아요 ㅜㅜ

그리고 저번에 말씀드린 내용은 변수선택기법은 너무 많으니깐 전체적으로 변수선택기법들 정리해서 올리는 것보다 
전에 보여드렸던 것 중에서 하나의 주제만 정리하면 어떨까 생각들어요. 예를 들면 null importance 만 블로그에서 다루면 어떨까 해요. 그런 거는 잘 모르는 기법이니깐 다들 관심있을 것 같아요!


오타/띄어쓰기 코멘트 드립니다! 수정 부탁드려요! 

아래는 대부분의 기계 학습 문제에 적용할 수 있는 포괄적이고 실질적인 접근 방식입니다.
=> 아래는 대부분의 기계학습 문제에 적용할 수 있는 포괄적이고 실질적인 접근 방식입니다.
(띄어쓰기)

신중하게 선택한 평가 기준을 사용하여 데이터 집합의 각 알고리즘의 성능을 비교하는 기계 학습 파이프라인을 설정해야 합니다. 
=> 신중하게 선택한 평가 기준을 사용하여 데이터 집합의 각 알고리즘의 성능을 비교하는 기계학습 파이프라인을 설정해야 합니다. 
(띄어쓰기)

하이퍼 매개 변수의 최적 회에는 grid search, Random search 및 Bayesian Optimization 3가지가 있습니다.
=> 하이퍼 매개변수의 최적화에는 grid search, Random search 및 Bayesian Optimization 3가지가 있습니다.
(최적 회, 오타 및 띄어쓰기)

비지도 학습은 진정한 인공 지능 (artificial intelligence)이라고 불리는 것과 밀접하게 관련되어 있습니다. 
=> 비지도 학습은 진정한 인공지능 (artificial intelligence)이라고 불리는 것과 밀접하게 관련되어 있습니다. 
(띄어쓰기)

(이 사실을 모르는 경우) 두 개의 그룹으로 나누고 싶다고 해 보겠습니다.
=> (이 사실을 모르는 경우) 두 개의 그룹으로 나누고 싶다고 해보겠습니다.
(해 보겠습니다 => 해보겠습니다.)

평균이 각 클러스터의 대다수에 가까우므로 둘째로 이동하면 한 그룹의 모든 내용은 사과가 되고 다른 그룹의 모든 내용물은 배가됩니다. 
=> 평균이 각 클러스터의 대다수에 가까우므로 둘째로 이동하면 한 그룹의 모든 내용은 사과가 되고 다른 그룹의 모든 내용물은 배가 됩니다. 
(배가됩니다 => 배가 됩니다)

반면, KNN은 지도 학습 중에서 분류문제를 풀기 위한 방법입니다.
=>반면, KNN은 지도학습 중에서 분류 문제를 풀기 위한 방법입니다.
(분류문제 => 분류 문제)

K-means에서 K는 우리가 결국 갖고 자하는 클러스터의 수를 의미합니다. K = 7인 경우, 데이터 집합에서 알고리즘을 실행하면 7개의 클러스터 그룹이 생성됩니다. 둘 다 K를 사용하는 알고리즘이지만 목적이 다른 점에서 우리를 혼동하게 합니다.
=> K-means에서 K는 우리가 결국 갖고자 하는 클러스터의 수를 의미합니다. K = 7인 경우, 데이터 집합에서 알고리즘을 실행하면 7개의 클러스터 그룹이 생성됩니다. 둘 다 K를 사용하는 알고리즘이지만 목적이 다른 점에서 우리를 혼동하게 합니다.
(갖고 자하는 => 갖고자 하는)


고생하셨습니다! 이정도 리뷰로 끝낼게요.. 4월에는 다음 글 준비해주심 될것 같아요.ㅎㅎ
해당 내용 수정 완료하시면 내용 변경해서 다시 푸시 해주시고 글 요약하셔서 페이스북에 포스팅 해주세요!

(페이스북 포스팅은 아래 참고할 것 : https://www.facebook.com/groups/databreak/permalink/2337634946491174/)

**Comment by choco9966** [comment]
fix #6
