### ISSUE TITLE
It’s Only Natural: An Excessively Deep Dive Into Natural Gradient Optimization

### ISSUE THREAD

**Issue by Youngpyoryu** [KaggleBreak/gatsby-casper#7]
## Title & Topic
Machine learning에 필요한 Gradient Optimization에 전반적인 설명 

## Upload schedule
3월 24일에 시작하여, 3월 31일날 끝내는 것을 목표로 합니다.

## Reference
https://towardsdatascience.com/its-only-natural-an-excessively-deep-dive-into-natural-gradient-optimization-75d464b89dbb

**Comment by syleeie2310** [comment]
@Youngpyoryu 님 혹시 올리셨나요?? 리뷰 해드려야 하는데 어여 부탁드려요!!ㅎㅎ

**Comment by syleeie2310** [comment]
주말까지 작성하셔서 저 호출하시면 제가 리뷰 해드릴게요! ㅎㅎ 부탁드려요 @Youngpyoryu 님

**Comment by syleeie2310** [comment]
번역 작성 완료하시면 https://github.com/KaggleBreak/databreak-blog/issues 에 새롭게 올려주시고 거기다가 md 파일 push 하시고 저한테 리뷰 요청 해주세요!

@Youngpyoryu 님!
