### ISSUE TITLE
Feature Selection with Null Importances

### ISSUE THREAD

**Issue by choco9966** [KaggleBreak/gatsby-casper#8]
## Title & Topic

캐글에서 점수를 올리기 위해서 변수제거(선택)법을 많이 사용합니다. 그 중에서 Target과 연관지어서 사용하는 Null importance라는 기법에 대해서 정리해보도록 하겠습니다. 

## Upload schedule

작성 시작 날짜 : 3월 30일 
업로드 날짜 : 4월 7일

## Reference

자료 : https://www.kaggle.com/ogrellier/feature-selection-with-null-importances

**Comment by syleeie2310** [comment]
이건 이슈 종료해주시고 https://github.com/KaggleBreak/databreak-blog/issues 에 새롭게 올려주세요

@choco9966
